/**
 * The WACL Theme, performed live. Fetches the league's own composition
 * (public/media/wacl-theme.mid, generated by scripts/wacl_theme.py) and plays
 * it through WebAudio with a synth voice per track — so the committed MIDI
 * stays the single source of truth and the 90-second loop wraps seamlessly.
 * Off by default; the footer MUSIC toggle is the only way it starts.
 */

const STORE_KEY = 'wacl.music'
const LOOKAHEAD_S = 0.4
const TICK_MS = 100

interface Note {
  t: number // seconds into the piece
  dur: number
  ch: number
  pitch: number
  vel: number // 0..1
}

interface Piece {
  notes: Note[]
  length: number
}

/** Music defaults ON; only an explicit toggle-off is remembered as off. */
export function musicOn(): boolean {
  try {
    return localStorage.getItem(STORE_KEY) !== 'off'
  } catch {
    return true
  }
}

export function setMusicOn(on: boolean): void {
  try {
    localStorage.setItem(STORE_KEY, on ? 'on' : 'off')
  } catch {
    /* private mode */
  }
  if (on) void start()
  else stop()
}

/* ------------------------------------------------------------------ *
 * MIDI parsing (just enough SMF for our own file)
 * ------------------------------------------------------------------ */

function parseMidi(buffer: ArrayBuffer): Piece {
  const data = new Uint8Array(buffer)
  const view = new DataView(buffer)
  const ppq = view.getUint16(12)
  const trackCount = view.getUint16(10)
  let tempo = 500_000
  const notes: Note[] = []
  let maxTick = 0

  let pos = 14
  for (let track = 0; track < trackCount; track++) {
    const length = view.getUint32(pos + 4)
    let i = pos + 8
    const end = i + length
    let tick = 0
    let running = 0
    const open = new Map<number, { tick: number; vel: number }>()

    const vlq = () => {
      let value = 0
      let byte
      do {
        byte = data[i++]
        value = (value << 7) | (byte & 0x7f)
      } while (byte & 0x80)
      return value
    }

    while (i < end) {
      tick += vlq()
      let status = data[i]
      if (status & 0x80) i++
      else status = running
      running = status

      if (status === 0xff) {
        const kind = data[i++]
        const len = vlq()
        if (kind === 0x51) tempo = (data[i] << 16) | (data[i + 1] << 8) | data[i + 2]
        i += len
      } else if ((status & 0xf0) === 0x90 || (status & 0xf0) === 0x80) {
        const ch = status & 0x0f
        const pitch = data[i++]
        const vel = data[i++]
        const key = ch * 128 + pitch
        if ((status & 0xf0) === 0x90 && vel > 0) {
          open.set(key, { tick, vel })
        } else {
          const began = open.get(key)
          if (began) {
            open.delete(key)
            notes.push({
              t: began.tick,
              dur: tick - began.tick,
              ch,
              pitch,
              vel: began.vel / 127,
            } as unknown as Note)
          }
        }
        maxTick = Math.max(maxTick, tick)
      } else if ((status & 0xf0) === 0xc0 || (status & 0xf0) === 0xd0) {
        i += 1
      } else {
        i += 2
      }
    }
    pos = end
  }

  const secPerTick = tempo / 1_000_000 / ppq
  for (const note of notes) {
    note.t *= secPerTick
    note.dur *= secPerTick
  }
  notes.sort((a, b) => a.t - b.t)
  // Round the loop length up to a whole bar so early note-offs can't shave
  // milliseconds off the wrap point.
  const ticksPerBar = ppq * 4
  const totalTicks = Math.ceil(maxTick / ticksPerBar) * ticksPerBar
  return { notes, length: totalTicks * secPerTick }
}

/* ------------------------------------------------------------------ *
 * Synth voices — one flavour per channel of the theme
 * ------------------------------------------------------------------ */

let ctx: AudioContext | null = null
let master: GainNode | null = null
let noiseBuffer: AudioBuffer | null = null
let piece: Piece | null = null
let timer: number | null = null
/** Bumped by stop() so an in-flight start() aborts instead of playing on. */
let generation = 0

function noise(context: AudioContext): AudioBuffer {
  if (noiseBuffer) return noiseBuffer
  noiseBuffer = context.createBuffer(1, context.sampleRate, context.sampleRate)
  const samples = noiseBuffer.getChannelData(0)
  for (let i = 0; i < samples.length; i++) samples[i] = Math.random() * 2 - 1
  return noiseBuffer
}

function freq(pitch: number): number {
  return 440 * 2 ** ((pitch - 69) / 12)
}

function tone(
  context: AudioContext,
  out: AudioNode,
  options: {
    type: OscillatorType
    freq: number
    detune?: number
    filter?: number
    gain: number
    when: number
    attack: number
    hold: number
    release: number
  },
): void {
  const osc = context.createOscillator()
  osc.type = options.type
  osc.frequency.value = options.freq
  if (options.detune) osc.detune.value = options.detune
  const amp = context.createGain()
  const t = options.when
  amp.gain.setValueAtTime(0, t)
  amp.gain.linearRampToValueAtTime(options.gain, t + options.attack)
  amp.gain.setValueAtTime(options.gain, t + options.attack + options.hold)
  amp.gain.linearRampToValueAtTime(0.0001, t + options.attack + options.hold + options.release)
  let head: AudioNode = amp
  if (options.filter) {
    const lp = context.createBiquadFilter()
    lp.type = 'lowpass'
    lp.frequency.value = options.filter
    osc.connect(lp)
    lp.connect(amp)
  } else {
    osc.connect(amp)
  }
  head.connect(out)
  osc.start(t)
  osc.stop(t + options.attack + options.hold + options.release + 0.05)
}

function hit(
  context: AudioContext,
  out: AudioNode,
  pitch: number,
  vel: number,
  when: number,
): void {
  if (pitch === 36) {
    // kick: sine drop with a click
    const osc = context.createOscillator()
    osc.type = 'sine'
    osc.frequency.setValueAtTime(140, when)
    osc.frequency.exponentialRampToValueAtTime(45, when + 0.11)
    const amp = context.createGain()
    amp.gain.setValueAtTime(0.5 * vel, when)
    amp.gain.exponentialRampToValueAtTime(0.001, when + 0.24)
    osc.connect(amp)
    amp.connect(out)
    osc.start(when)
    osc.stop(when + 0.26)
    return
  }
  // noise-based: snare and hats
  const src = context.createBufferSource()
  src.buffer = noise(context)
  const filter = context.createBiquadFilter()
  const amp = context.createGain()
  let decay = 0.05
  let gain = 0.12 * vel
  if (pitch === 38) {
    filter.type = 'bandpass'
    filter.frequency.value = 1900
    decay = 0.14
    gain = 0.3 * vel
  } else {
    filter.type = 'highpass'
    filter.frequency.value = pitch === 46 ? 6500 : 7500
    decay = pitch === 46 ? 0.22 : 0.045
  }
  amp.gain.setValueAtTime(gain, when)
  amp.gain.exponentialRampToValueAtTime(0.001, when + decay)
  src.connect(filter)
  filter.connect(amp)
  amp.connect(out)
  src.start(when, Math.random(), decay + 0.05)
}

function playNote(context: AudioContext, out: AudioNode, note: Note, when: number): void {
  const f = freq(note.pitch)
  const dur = Math.max(0.05, note.dur)
  switch (note.ch) {
    case 0: // bass engine: saw + square sub under a dark lowpass
      tone(context, out, { type: 'sawtooth', freq: f, filter: 380, gain: 0.4 * note.vel, when, attack: 0.004, hold: dur * 0.85, release: 0.04 })
      tone(context, out, { type: 'square', freq: f / 2, filter: 240, gain: 0.22 * note.vel, when, attack: 0.004, hold: dur * 0.85, release: 0.04 })
      return
    case 1: // arp: bright saw pluck
      tone(context, out, { type: 'sawtooth', freq: f, filter: 2400, gain: 0.14 * note.vel, when, attack: 0.003, hold: dur * 0.4, release: dur * 0.5 })
      return
    case 4: // peak arp double, airier and quieter
      tone(context, out, { type: 'sawtooth', freq: f, filter: 3400, gain: 0.08 * note.vel, when, attack: 0.003, hold: dur * 0.4, release: dur * 0.5 })
      return
    case 2: // lead: two softly detuned triangles
      tone(context, out, { type: 'triangle', freq: f, detune: -4, gain: 0.16 * note.vel, when, attack: 0.02, hold: dur * 0.8, release: 0.1 })
      tone(context, out, { type: 'triangle', freq: f, detune: 5, gain: 0.16 * note.vel, when, attack: 0.02, hold: dur * 0.8, release: 0.1 })
      return
    case 3: // pad: slow detuned saws
      tone(context, out, { type: 'sawtooth', freq: f, detune: -8, filter: 900, gain: 0.055 * note.vel, when, attack: 0.35, hold: dur * 0.6, release: 0.35 })
      tone(context, out, { type: 'sawtooth', freq: f, detune: 8, filter: 900, gain: 0.055 * note.vel, when, attack: 0.35, hold: dur * 0.6, release: 0.35 })
      return
    case 9:
      hit(context, out, note.pitch, note.vel, when)
      return
  }
}

/* ------------------------------------------------------------------ *
 * Transport: lookahead scheduler with a seamless loop
 * ------------------------------------------------------------------ */

/**
 * Notes scheduled into the near future, kept so the UI can dance to them.
 * meterLevels() folds them into three band levels (bass / lead / high) that
 * decay over ~350ms after each onset — enough for equalizer bars to bounce
 * in time with what is actually sounding.
 */
const liveNotes: { t: number; pitch: number; vel: number }[] = []

export function meterLevels(): [number, number, number] {
  if (!ctx || timer === null) return [0, 0, 0]
  const now = ctx.currentTime
  const bands: [number, number, number] = [0, 0, 0]
  for (const note of liveNotes) {
    const age = now - note.t
    if (age < 0 || age > 0.35) continue
    const level = (1 - age / 0.35) * (0.4 + 0.6 * note.vel)
    const band = note.pitch < 48 ? 0 : note.pitch < 66 ? 1 : 2
    if (level > bands[band]) bands[band] = level
  }
  return bands
}

async function loadPiece(): Promise<Piece> {
  if (piece) return piece
  const response = await fetch(`${import.meta.env.BASE_URL}media/wacl-theme.mid`)
  if (!response.ok) throw new Error('theme unavailable')
  piece = parseMidi(await response.arrayBuffer())
  return piece
}

export async function start(): Promise<void> {
  if (timer !== null) return
  const myGeneration = ++generation
  // Autoplay policy: the context must be created and resumed synchronously
  // inside the user's gesture — an await first breaks the activation chain
  // and the context comes up suspended (i.e. silent) forever.
  ctx = ctx ?? new AudioContext()
  if (ctx.state === 'suspended') void ctx.resume()

  const theme = await loadPiece().catch(() => null)
  if (!theme || theme.notes.length === 0) return
  // stop() ran, or another start() won, while the MIDI was loading
  if (myGeneration !== generation || !ctx || timer !== null) return

  master = ctx.createGain()
  master.gain.value = 0.9
  const glue = ctx.createDynamicsCompressor()
  glue.threshold.value = -18
  master.connect(glue)
  glue.connect(ctx.destination)

  const startAt = ctx.currentTime + 0.1
  let index = 0
  let loop = 0
  let scheduled = 0

  // Tiny console-inspectable health probe: state must read 'running' and
  // time must advance, or the context is suspended and nothing is audible.
  ;(window as unknown as Record<string, unknown>).__waclMusic = {
    state: () => ctx?.state,
    time: () => ctx?.currentTime,
    scheduled: () => scheduled,
  }

  const pump = () => {
    if (!ctx || !master) return
    const horizon = ctx.currentTime + LOOKAHEAD_S
    while (true) {
      if (index >= theme.notes.length) {
        index = 0
        loop += 1
      }
      const note = theme.notes[index]
      const when = startAt + loop * theme.length + note.t
      if (when > horizon) break
      playNote(ctx, master, note, when)
      liveNotes.push({ t: when, pitch: note.pitch, vel: note.vel })
      if (liveNotes.length > 240) liveNotes.splice(0, 120)
      scheduled += 1
      index += 1
    }
  }

  pump()
  timer = window.setInterval(pump, TICK_MS)
}

export function stop(): void {
  generation += 1 // aborts any start() still awaiting its fetch
  if (timer !== null) {
    clearInterval(timer)
    timer = null
  }
  if (ctx) {
    const dying = ctx
    if (master) {
      // fade, then close; a context with no master yet just closes
      master.gain.setTargetAtTime(0, dying.currentTime, 0.06)
      window.setTimeout(() => void dying.close().catch(() => undefined), 400)
    } else {
      void dying.close().catch(() => undefined)
    }
  }
  ctx = null
  master = null
  noiseBuffer = null
}
